var info = [
  {
    nome: "Livello 1: Primi Passi",
    desc1: "Nessuno ti disturberà. È il momento di imparare senza fretta.",
    tempo: "2:00",
    moduli: "3",
    errori: "3",
    difficolta: "Easy",
    link: "/html/bomba/livello1.html",
  },
  {
    nome: "Livello 2: Piccole Distrazioni",
    desc1: "Un piccolo disturbo non dovrebbe preoccuparti… o sì?",
    tempo: "3:00",
    moduli: "4",
    errori: "3",
    difficolta: "Easy",
    link: "/html/bomba/livello2.html",
  },
  {
    nome: "Livello 3: L’Alba del Caos",
    desc1: "Hai imparato le basi. Ora prova a gestire un po’ di pressione!",
    tempo: "4:00",
    moduli: "5",
    errori: "2",
    difficolta: "Easy",
    link: "/html/bomba/livello3.html",
  },
  {
    nome: "Livello 4: Equilibrio Fragile",
    desc1: "Semplice, ma con un pizzico di sfida. Concentrati!",
    tempo: "3:30",
    moduli: "4",
    errori: "3",
    difficolta: "Media",
    link: "/html/bomba/livello4.html",
  },
  {
    nome: "Livello 5: Tra Due Fuochi",
    desc1: "Distrazioni in aumento. Mantieni il sangue freddo!",
    tempo: "4:30",
    moduli: "5",
    errori: "2",
    difficolta: "Media",
    link: "/html/bomba/livello5.html",
  },
  {
    nome: "Livello 6: Sotto Pressione",
    desc1: "Il ritmo accelera. Sei pronto per una sfida più seria?",
    tempo: "5:00",
    moduli: "6",
    errori: "2",
    difficolta: "Media",
    link: "/html/bomba/livello6.html",
  },
  {
    nome: "Livello 7: La Calma Prima della Tempesta",
    desc1: "I primi enigmi difficili si affacciano all’orizzonte. Resisti!",
    tempo: "4:30",
    moduli: "5",
    errori: "2",
    difficolta: "Media",
    link: "/html/bomba/livello7.html",
  },
  {
    nome: "Livello 8: Nel Cuore della Tempesta",
    desc1: "La pressione aumenta. Riuscirai a non perdere il controllo?",
    tempo: "5:30",
    moduli: "6",
    errori: "1",
    difficolta: "Media",
    link: "/html/bomba/livello8.html",
  },
  {
    nome: "Livello 9: Campo Minato",
    desc1: "Ogni passo è cruciale. Non sbagliare!",
    tempo: "6:00",
    moduli: "7",
    errori: "1",
    difficolta: "Media",
    link: "/html/bomba/livello8.html",
  },
  {
    nome: "Livello 10: Il Fuoco del Conflitto",
    desc1: "Difficile, ma non impossibile. Preparati a sudare.",
    tempo: "5:30",
    moduli: "6",
    errori: "1",
    difficolta: "Difficile",
    link: "/html/bomba/livello10.html",
  },
  {
    nome: "Livello 11: Apice della Tensione",
    desc1: "Ogni errore ti costerà caro. Gioca con precisione",
    tempo: "6:00",
    moduli: "8",
    errori: "0",
    difficolta: "Difficile",
    link: "/html/bomba/livello11.html",
  },
  {
    nome: "Livello 12: Occhio del Ciclone",
    desc1: "Difficoltà estrema. Solo i più calmi possono sopravvivere.",
    tempo: "6:00",
    moduli: "10",
    errori: "0",
    difficolta: "Difficile",
    link: "/html/bomba/livello12.html",
  },
  {
    nome: "Livello 13: La Forgia dell’Eroe",
    desc1: "Il fuoco è caldo, ma sei forgiato per affrontarlo. Dimostra il tuo valore.",
    tempo: "5:30",
    moduli: "8",
    errori: "0",
    difficolta: "Leggendario",
    link: "/html/bomba/livello13.html",
  },
  {
    nome: "Livello 14: Punto di Non Ritorno",
    desc1: "Ogni decisione conta. Ogni istante è critico. Sei all’altezza?",
    tempo: "5:30",
    moduli: "10",
    errori: "0",
    difficolta: "Leggendario",
    link: "/html/bomba/livello14.html",
  },
  {
    nome: "Livello 15: L’Olimpo della Gloria",
    desc1: "Ogni decisione conta. Ogni istante è critico. Sei all’altezza?",
    tempo: "6:00",
    moduli: "11",
    errori: "0",
    difficolta: "Leggendario",
    link: "/html/bomba/livello15.html",
  }, 
];
