var info = [
  {
    nome: "Livello 1: Primi Passi",
    desc1: "Nessuno ti disturberà. È il momento di imparare senza fretta.",
    tempo: "2:00",
    moduli: "3",
    errori: "3",
    difficolta: "Easy",
    link: "/html/bomba/livello1.html",
  },
  {
    nome: "Livello 2: Piccole Distrazioni",
    desc1: "Un piccolo disturbo non dovrebbe preoccuparti… o sì?",
    tempo: "3:00",
    moduli: "4",
    errori: "3",
    difficolta: "Easy",
    link: "/html/bomba/livello2.html",
  },
  {
    nome: "Livello 3: L’Alba del Caos",
    desc1: "Hai imparato le basi. Ora prova a gestire un po’ di pressione!",
    tempo: "4:00",
    moduli: "5",
    errori: "2",
    difficolta: "Easy",
    link: "/html/bomba/livello3.html",
  },
  {
    nome: "Livello 4: Equilibrio Fragile",
    desc1: "Semplice, ma con un pizzico di sfida. Concentrati!",
    tempo: "3:30",
    moduli: "4",
    errori: "3",
    difficolta: "Media",
    link: "/html/bomba/livello4.html",
  },
  {
    nome: "Livello 5: Tra Due Fuochi",
    desc1: "Distrazioni in aumento. Mantieni il sangue freddo!",
    tempo: "4:30",
    moduli: "5",
    errori: "2",
    difficolta: "Media",
    link: "/html/bomba/livello5.html",
  },
  {
    nome: "Livello 6: Sotto Pressione",
    desc1: "Il ritmo accelera. Sei pronto per una sfida più seria?",
    tempo: "5:00",
    moduli: "6",
    errori: "2",
    difficolta: "Media",
    link: "/html/bomba/livello6.html",
  },
];
