var solutions = [
  {
    white: [
      { piece: 4, cell: 32 },
      { piece: 3, cell: 16 },
      { piece: 2, cell: 18 },
    ],
    black: [
      { piece: 4, cell: 9 },
      { piece: 5, cell: 1 },
    ],
    moves: [
      {
        piece: 3,
        prevCell: 16,
        currentCell: 0,
        player: "white",
        notation: "Rh1+",
        king: 1,
      },
      {
        piece: 4,
        prevCell: 9,
        currentCell: 0,
        player: "black",
        notation: "Qxh1",
        king: 1,
      },
      {
        piece: 4,
        prevCell: 32,
        currentCell: 0,
        player: "white",
        notation: "Qxh1#",
        king: 1,
      },
    ],
  },
  {
    white: [
      { piece: 0, cell: 40 },
      { piece: 3, cell: 9 },
      { piece: 1, cell: 35 },
      { piece: 0, cell: 41 },
    ],
    black: [
      { piece: 5, cell: 25 },
      { piece: 0, cell: 17 },
      { piece: 4, cell: 20 },
    ],
    moves: [
      {
        piece: 0,
        prevCell: 40,
        currentCell: 32,
        player: "white",
        notation: "h5+",
        king: 25,
      },
      {
        piece: 5,
        prevCell: 25,
        currentCell: 18,
        player: "black",
        notation: "Kf3",
        king: 18,
      },
      {
        piece: 3,
        prevCell: 9,
        currentCell: 17,
        player: "white",
        notation: "Rxg3+",
        king: 18,
      },
      {
        piece: 5,
        prevCell: 18,
        currentCell: 27,
        player: "black",
        notation: "Ke4",
        king: 27,
      },
      {
        piece: 3,
        prevCell: 17,
        currentCell: 20,
        player: "white",
        notation: "Rxd3#",
        king: 27,
      },
    ],
  },
  {
    white: [
      { piece: 2, cell: 46 },
      { piece: 0, cell: 39 },
      { piece: 0, cell: 32 },
      { piece: 5, cell: 10 },
    ],
    black: [
      { piece: 3, cell: 4 },
      { piece: 2, cell: 0 },
      { piece: 5, cell: 8 },
      { piece: 0, cell: 16 },
      { piece: 1, cell: 19 },
      { piece: 3, cell: 27 },
    ],
    moves: [
      {
        piece: 2,
        prevCell: 46,
        currentCell: 53,
        player: "white",
        notation: "bc7+",
        king: 8,
      },
      {
        piece: 3,
        prevCell: 4,
        currentCell: 44,
        player: "black",
        notation: "rd6",
        king: 8,
      },
      {
        piece: 2,
        prevCell: 53,
        currentCell: 44,
        player: "white",
        notation: "bxd6+",
        king: 8,
      },
      {
        piece: 3,
        prevCell: 27,
        currentCell: 26,
        player: "black",
        notation: "rf4",
        king: 8,
      },
      {
        piece: 2,
        prevCell: 44,
        currentCell: 26,
        player: "white",
        notation: "bxf4#",
        king: 8,
      },
    ],
  },
  {
    white: [
      { piece: 4, cell: 37 },
      { piece: 3, cell: 58 },
      { piece: 5, cell: 56 },
    ],
    black: [
      { piece: 5, cell: 1 },
      { piece: 0, cell: 8 },
      { piece: 0, cell: 9 },
      { piece: 0, cell: 10 },
      { piece: 3, cell: 5 },
    ],
    moves: [
      {
        piece: 4,
        prevCell: 37,
        currentCell: 10,
        player: "white",
        notation: "Qxf2+",
        king: 1,
      },
      {
        piece: 5,
        prevCell: 1,
        currentCell: 0,
        player: "black",
        notation: "Kh1",
        king: 0,
      },
      {
        piece: 4,
        prevCell: 10,
        currentCell: 2,
        player: "white",
        notation: "Qf1",
        king: 0,
      },
      {
        piece: 3,
        prevCell: 5,
        currentCell: 2,
        player: "black",
        notation: "rxf1",
        king: 0,
      },
      {
        piece: 3,
        prevCell: 58,
        currentCell: 2,
        player: "white",
        notation: "Rxf1#",
        king: 0,
      },
    ],
  },
];

var pieces = ["p", "N", "B", "R", "Q", "K"];
